import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ErrorContextProvider from "@/store/ErrorContextProvided";
import ContextProvider from "./ContextProvider";
import Toast from "@/components/Toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  {
    /* h-full antialiased */
  }
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} `}>
      <body className="min-h-full flex flex-col">
        <ContextProvider>
          <Toast />
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
